version: '2'

services:
  telegram-proxy:
    image: telegrammessenger/proxy:latest
    container_name: mtproto-proxy
    restart: unless-stopped
    ports:
      - "10443:443"
      - "2398:2398"
    volumes:
      - "./proxy-config:/data"
    env_file:
      - "./config.env"
