version: '2'

services:
  telegram-proxy:
    image: telegrammessenger/proxy:latest
    container_name: mtproto-proxy
    restart: always
    ports:
      - "10.0.5.2:443:443"
    networks:
      tp_net:
        ipv4_address: 10.0.5.2
    volumes:
      - "./proxy-config:/data"

networks:
  tp_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.5.0/30
         gateway: 10.0.5.1